INSERT INTO MUSICIAN (FIRST_NAME, LAST_NAME, DOB, MUSICIAN_TYPE) VALUES ('Ayondeep', 'Datta','1980-01-22', 'Mohan Veena');
INSERT INTO MUSICIAN (FIRST_NAME, LAST_NAME, DOB, MUSICIAN_TYPE) VALUES ('Ravi', 'Shankar', '1960-01-01', 'Sitar');
